apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    app: mongo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-deploy
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017