apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-ns-quota
  namespace: dev-team
spec:
  hard: 
    requests.cpu: "1"
    requests.memory: "1Gi" #1GB = 1024KB, 1Gi = 1000KB
    limits.cpu: "2" 
    limits.memory: "2Gi"
    pods: "10"