- name: create a user with hashed pass
  hosts: clients
  remote_user: root
  vars:
    secret: Secure*123
  
  tasks:
  - name: create a new user account
    user:
      name: user11
      password: "{{ secret | password_hash('sha512') }}"
      state: present