- name: create a user with hashed pass and secret file encryption
  hosts: clients
  remote_user: root
  vars_files:
    - secret.yaml
  
  tasks:
  - name: create a new user account
    user:
      name: user13
      password: "{{ secret | password_hash('sha512') }}"
      state: present