apiVersion: v1
kind: PersistentVolume 
metadata:
  name: file-store-vol 
spec: 
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01
    server: 10.227.28.34
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: file-store-vol-claim