apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-pod-affinity
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-app
        image: httpd
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
        - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: gpuenabled
              labelSelector:
                matchExpressions:
                  - key: app 
                    operator: In 
                    values: 
                    - httpd-app

# kubectl label node <node_name> gpuenabled=true