apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: dynamic-disk-pvc
spec:
  resources: 
    requests: 
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-pd-sc