- name: Install nginx
  hosts: clients
  remote_user: root 

  tasks:
  - name: Running apt-update
    apt:
      update-cache: yes
  
  - name: Install nginx
    apt:
      pkg: nginx
      state: present